
#Locators de urbanroutespage
urban_routes_url = 'https://5e2a7270-b004-470d-8a6e-bd6d57789e90.serverhub.tripleten-services.com?lng=es'
locator_from='from'
locator_to='to'
css_button_taxi='.button.round'
address_from = 'East 2nd Street, 601'
address_to = '1300 1st St'
phone_number = '+1 123 123 12 12'
css_telephone='.np-button'
id_phone='phone'
css_next='.button.full'
id_code='code'
card_number, card_code = '1234 5678 9100', '111'
message_for_driver = 'Muéstrame el camino al museo'
personal='/html/body/div/div/div[3]/div[3]/div[1]/div[1]/div[3]'
comfort='/html/body/div[1]/div/div[3]/div[3]/div[2]/div[1]/div[5]'
xpath_button_confirm='/html/body/div/div/div[1]/div[2]/div[2]/form/div[2]/button[1]'
css_click_payment='.pp-text'
css_click_add_card='.pp-row.disabled'
id_number_card='number'
css_code_card='.card-code-input .card-input'
xpath_link='/html/body/div/div/div[2]/div[2]/div[2]/form/div[3]/button[1]'
xpath_close='/html/body/div/div/div[2]/div[2]/div[1]/button'
id_comment="comment"
xpath_manta='/html/body/div/div/div[3]/div[3]/div[2]/div[2]/div[4]/div[2]/div[1]/div/div[2]/div/span'
css_selected_slider='.switch-input:checked+.slider'
xpath_helado='/html/body/div/div/div[3]/div[3]/div[2]/div[2]/div[4]/div[2]/div[3]/div/div[2]/div[1]/div/div[2]/div/div[3]'
css_counter_ice_cream='.counter-value'
css_button_order='.smart-button-main, .smart-button-secondary'

#Locators de testpageurban
css_number_telephone='.np-text'
css_credit_card_text='.pp-value-text'
css_modal_element='.order-header-content'